# Generated by Django 6.0.3 on 2026-03-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('funcionario', 'Funcionário')], default='funcionario', max_length=20),
        ),
    ]
