# Generated by Django 6.0.3 on 2026-03-26 15:29

import apps.empresa.validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[apps.empresa.validator.validar_cnpj])),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, null=True)),
                ('cnae_principal', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('moeda_padrao', models.CharField(choices=[('BRL', 'Real Brasileiro'), ('USD', 'Dólar Americano'), ('EUR', 'Euro')], default='BRL', max_length=3)),
                ('certificado_digital', models.FileField(blank=True, null=True, upload_to='empresas/certificados/')),
                ('senha_certificado', models.CharField(blank=True, max_length=255, null=True)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('pais', models.CharField(default='Brasil', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('regime_tributario', models.CharField(choices=[('SN', 'Simples Nacional'), ('LP', 'Lucro Presumido'), ('LR', 'Lucro Real')], max_length=2)),
                ('tipo_empresa', models.CharField(choices=[('MATRIZ', 'Matriz'), ('FILIAL', 'Filial')], default='MATRIZ', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('matriz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiais', to='empresa.empresa')),
            ],
        ),
    ]
